#!/usr/bin/env perl
use strict;
use warnings;
use Compress::Zlib;

binmode STDIN;
binmode STDOUT;

my $x = inflateInit() or die "Can not create a inflation stream";

my $status;
while (1) {
	my $res = read(STDIN, my $buffer, 4096) // die "Can not read from stream";
	if ($res == 0) {
		die "Inflation failed" unless $status == Z_STREAM_END;
		last;
	}
	(my $output, $status) = $x->inflate($buffer);
	if ($status == Z_OK) {
		print $output;
	} elsif ($status == Z_STREAM_END) {
		print $output;
		my $res2 = read(STDIN, my $buffer, 1) // die "Can not read from stream";
		die "Inflation failed" unless $res2 == 0;
		last;
	} else {
		die "Inflation failed";
	}
}
